; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags = 
	-D BOARD_REV=2
	-D NET=-1  ; 0-лорп 1-сим 2-лорасим
	-D BOARD_TYPE=0 ;0 - полевой 1 - головной
	;     -DSerial=Dual
    ; -Wno-unused-variable
lib_deps = 
	xreef/EByte LoRa E220 library@^1.0.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
	knolleary/PubSubClient@^2.8
	plerup/EspSoftwareSerial@^8.2.0
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
